name: Run Tests

on: [push]

jobs:
  run-tests:
    runs-on: openhpc-lenovo-repo

    steps:
      - name: First
        run:
          hostname
      - uses: actions/checkout@v3
      - name: Second
        run:
          ./run-tests.sh
